// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEETrUz-lrcplJlQ0YuuufTktAMamE3ww',
    appId: '1:125218567647:web:5ec655d9bd0efc0758006a',
    messagingSenderId: '125218567647',
    projectId: 'cenacle-link-app',
    authDomain: 'cenacle-link-app.firebaseapp.com',
    storageBucket: 'cenacle-link-app.firebasestorage.app',
    measurementId: 'G-V4WEFBN78W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcIYJN-8O5aAiAxLrEML5uHNEDcH8Q_6c',
    appId: '1:125218567647:android:34ea8b660880c99458006a',
    messagingSenderId: '125218567647',
    projectId: 'cenacle-link-app',
    storageBucket: 'cenacle-link-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApzAUnIt0ff3rd2OIptbWK_Ok-olc4IS8',
    appId: '1:125218567647:ios:99cf64e7094e9eaa58006a',
    messagingSenderId: '125218567647',
    projectId: 'cenacle-link-app',
    storageBucket: 'cenacle-link-app.firebasestorage.app',
    iosClientId:
        '125218567647-qa3ql3nlian7lqch0amo7svvdgkjnpar.apps.googleusercontent.com',
    iosBundleId: 'com.cinacle.app',
  );
}
